changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
        - 'fix'
    - title: '🔧 Maintenance'
      labels:
        - 'chore'
        - 'refactor'
        - 'ci'
    - title: '📦 Dependencies'
      labels:
        - 'dependencies'
        - 'deps'
    - title: '📖 Documentation'
      labels:
        - 'docs'
    - title: 'Other Changes'
      labels:
        - '*'
