name-template: "v$RESOLVED_VERSION 🚀"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "✨ Features"
    labels: ["feature"]
  - title: "🐛 Bug Fixes"
    labels: ["bug"]
  - title: "📚 Documentation"
    labels: ["documentation"]
  - title: "🔧 Chores"
    labels: ["chore"]
  - title: "📦 Dependencies"
    labels: ["dependencies"]

# CRITICAL: This template forces commit-based display
template: |
  ## What's Changed
  
  $CATEGORIES

# Simple change template without PR references
change-template: |
  - $TITLE by @$AUTHOR

# Category template with emoji headers
category-template: |
  ## $TITLE
  $COMMITS

# Force commit parsing (most important setting)
commit-parser:
  pattern: "^(\w+)(?:\\(([\\w\\-\\.]+)\\))?!?:\\s*(.+)$"
  map:
    feat: "✨ Features"
    fix: "🐛 Bug Fixes"
    docs: "📚 Documentation"
    chore: "🔧 Chores"
    deps: "📦 Dependencies"

# Add emojis to each commit line
replacers:
  - search: '^- '
    replace: |-
      ${{
        (commit.match(/^feat:/) || commit.match(/^feature:/)) && '- ✨ ' ||
        (commit.match(/^fix:/) || commit.match(/^bug:/)) && '- 🐛 ' ||
        (commit.match(/^docs:/) || commit.match(/^documentation:/)) && '- 📚 ' ||
        (commit.match(/^chore:/) || commit.match(/^maintenance:/)) && '- 🔧 ' ||
        (commit.match(/^deps:/) || commit.match(/^dependencies:/)) && '- 📦 ' ||
        '- 📋 '
      }}

# Exclude merge commits and other noise
exclude:
  commits:
    - "^Merge"
    - "^Revert"
    - "^chore\\(release\\):"
    - "^docs\\(changelog\\):"

# Include author but not PR numbers
include:
  commit-hash: false
  commit-author: true
  commit-date: false
  pull-request-number: false  # ← CRITICAL: Disable PR numbers
  pull-request-title: false   # ← CRITICAL: Disable PR titles

sort:
  by: "date"
  order: "desc"
