changelog:
  exclude:
    labels: ["skip-release", "chore", "ci"]

  categories:
    # Module-specific categories FIRST
    - title: "🏗️ Origination - Bug Fixes"
      labels: ["bug", "origination"]
      
    - title: "🏗️ Origination - Features"
      labels: ["feature", "origination"]

    - title: "🔧 Maintenance - Bug Fixes"
      labels: ["bug", "maintenance"]

    - title: "🔧 Maintenance - Features"
      labels: ["feature", "maintenance"]

    - title: "🖥️ Attestation - Bug Fixes"
      labels: ["bug", "attestation"]

    - title: "🖥️ Attestation - Features"
      labels: ["feature", "attestation"]

    # General fallbacks (without module tags)
    - title: "🐞 Other Bug Fixes"
      labels: ["bug"]
      
    - title: "✨ Other Features"
      labels: ["feature"]

    - title: "📦 Dependency Updates"
      labels: ["dependencies"]
      collapse: true
