name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  ## What's Changed
  $CHANGES

categories:
  - title: "🚨 Breaking Changes"
    labels: ["breaking-change"]
  - title: "✨ Features"
    labels: ["feature"]
  - title: "🐛 Bug Fixes"
    labels: ["bug"]
  - title: "🛠 Enhancements"
    labels: ["enhancement"]
  - title: "📦 Dependencies"
    labels: ["dependencies"]
    collapse-after: 2
  - title: "📋 Other Changes"
    labels: []

# Change template to include commit messages
change-template: |
  - **$TITLE**$IS_MODULE – #$NUMBER
    $COMMIT_MESSAGES

# Custom template variables
template-variables:
  IS_MODULE: $IS_MODULE_TEMPLATE
  COMMIT_MESSAGES: $COMMIT_MESSAGES_TEMPLATE

# Replacers for module labels and commit messages
replacers:
  - search: '\$IS_MODULE_TEMPLATE'
    replace: >-
      ${{
        contains(labels, 'origination') && ' (`origination`)' ||
        contains(labels, 'maintenance') && ' (`maintenance`)' ||
        contains(labels, 'testation') && ' (`testation`)' ||
        ''
      }}
  
  - search: '\$COMMIT_MESSAGES_TEMPLATE'
    replace: >-
      ${{
        // Extract commit messages for this PR
        const commitMessages = commits.map(commit => 
          '  - ' + commit.message.split('\n')[0].trim()
        );
        commitMessages.length > 0 ? '\n' + commitMessages.join('\n') : ''
      }}

# Basic configuration
include-paths: []
exclude-labels: []
sort-direction: ascending
sort-by: merged_at
