name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Use conventional changelog plugin
plugins:
  "@release-it/conventional-changelog":
    preset: "conventionalcommits"
    infile: "CHANGELOG.md"
    header: "# Changelog"
    types:
      - type: "feat"
        section: "🚀 Features"
      - type: "fix"
        section: "🐛 Bug Fixes"
      - type: "docs"
        section: "📚 Documentation"
      - type: "style"
        section: "🎨 Code Style"
      - type: "refactor"
        section: "🔧 Refactors"
      - type: "perf"
        section: "⚡ Performance"
      - type: "test"
        section: "✅ Tests"
      - type: "build"
        section: "📦 Build System"
      - type: "ci"
        section: "🔧 CI/CD"
      - type: "chore"
        section: "🧹 Chores"
      - type: "revert"
        section: "⏪ Reverts"

# GitHub configuration
github:
  release: true
  preRelease: false
  draft: false
  releaseNotes: |
    # v$RESOLVED_VERSION ($(date +'%Y-%m-%d'))
    
    ## What's Changed
    
    $CHANGES
    
    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

# Git configuration
git:
  requireCleanWorkingDir: false
  commitMessage: "chore: release v${version}"
  tagAnnotation: "Release v${version}"

# Exclude skip-changelog labeled PRs
exclude-labels: ["skip-changelog", "ignore-changelog"]

# Sorting
sort-direction: ascending
sort-by: committed_date
