changelog:
  exclude:
    labels: ["skip-release", "chore", "ci"]

  categories:
    # Existing functional categories
    - title: "⚠️ BREAKING CHANGES"
      labels: ["breaking-change"]

    - title: "✨ New Features"
      labels: ["feature", "enhancement"]
      
    - title: "🐞 Defect Fixes"
      labels: ["bug", "hotfix"]

    - title: "🔄 API Updates"
      labels: ["api-update"]

    - title: "📦 Dependency Updates"
      labels: ["dependencies"]
      collapse: true

    - title: "📚 Documentation"
      labels: ["documentation"]
      collapse: true

    # New collapsible module sections
    - title: "🏗️ Public Origination"
      labels: ["origination"]
      collapse: true

    - title: "🔧 Public Maintenance"
      labels: ["maintenance"]
      collapse: true

    - title: "🖥️ Attestation UI"
      labels: ["attestation"]
      collapse: true

    - title: "⚙️ Other Changes"
      labels: ["*"]
