name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
 
categories:
  - title: "🚨 Breaking Changes"
    labels: ["breaking-change"]
  - title: "✨ Features"
    labels: ["feature"]
  - title: "🐛 Bug Fixes"
    labels: ["bug"]
  - title: "🛠 Enhancements"
    labels: ["enhancement"]
  - title: "📦 Dependencies"
    labels: ["dependencies"]
    collapse-after: 2
  - title: "📋 Other Changes"
    labels: []
    # fallback bucket when PRs don't match above categories
 
label-extractors:
  module:
    labels:
      - origination
      - maintenance
      - testation
 
change-template: |
  - $TITLE$IS_MODULE – #$NUMBER
 
# Template if there are no matching PRs
no-changes-template: "No significant changes."
 
# Define custom template variables
template-variables:
  # If $MODULE is defined, prefix it in brackets
  IS_MODULE: $IS_MODULE_TEMPLATE
 
# Custom rendering logic for module label (optional)
replacers:
  - search: '\$IS_MODULE_TEMPLATE'
    replace: >-
      ${{
        contains(labels, 'origination') && ' (`origination`)' ||
        contains(labels, 'maintenance') && ' (`maintenance`)' ||
        contains(labels, 'testation') && ' (`testation`)' ||
        ''
      }}
