name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

hooks:
  before:init: "node generate-changelog.js > CHANGELOG.md"

github:
  release: true
  releaseNotes: "cat CHANGELOG.md"

git:
  requireCleanWorkingDir: false
  commitMessage: "chore: release v${version}"
  tagAnnotation: "Release v${version}"
