changelog:
  categories:
    - title: "⚠️ BREAKING CHANGES"
      labels: ["breaking-change"]

    - title: "✨ New Features"
      labels: ["feature", "enhancement"]
      
    - title: "🐛 Defect Fixes"
      labels: ["bug", "hotfix"]

    - title: "🔄 API Updates"
      labels: ["api-update"]
      collapse: false

    - title: "📦 Dependency Updates"
      labels: ["dependencies"]
      collapse: true

    - title: "📚 Documentation"
      labels: ["documentation"]
      collapse: true

    - title: "⚙️ Other Changes"
      labels: ["*"]
