# .github/release-drafter.yml
template: |
  # Release Notes ($RESOLVED_VERSION)
  
  ## 🏗️ Origination
  ### Bug Fixes
  ${{#each (filter commits labels="bug,origination")}}
  - ${{subject}} (#${{pullRequest.number}})
  ${{/each}}

  ### Features
  ${{#each (filter commits labels="feature,origination")}}
  - ${{subject}} (#${{pullRequest.number}})
  ${{/each}}

  ## 🔧 Maintenance
  ### Bug Fixes
  ${{#each (filter commits labels="bug,maintenance")}}
  - ${{subject}} (#${{pullRequest.number}})
  ${{/each}}

  ### Features
  ${{#each (filter commits labels="feature,maintenance")}}
  - ${{subject}} (#${{pullRequest.number}})
  ${{/each}}

  ## 🖥️ Attestation
  ### Bug Fixes
  ${{#each (filter commits labels="bug,attestation")}}
  - ${{subject}} (#${{pullRequest.number}})
  ${{/each}}

  ### Features
  ${{#each (filter commits labels="feature,attestation")}}
  - ${{subject}} (#${{pullRequest.number}})
  ${{/each}}

  <details>
  <summary>📦 Other Changes (${{count (filter commits labels="!bug,!feature,!origination,!maintenance,!attestation")}})</summary>
  
  ### Dependencies
  ${{#each (filter commits labels="dependencies")}}
  - ${{subject}} (#${{pullRequest.number}})
  ${{/each}}

  ### Documentation
  ${{#each (filter commits labels="documentation")}}
  - ${{subject}} (#${{pullRequest.number}})
  ${{/each}}

  ### Uncategorized
  ${{#each (filter commits labels="!bug,!feature,!origination,!maintenance,!attestation,!dependencies,!documentation")}}
  - ${{subject}} (#${{pullRequest.number}})
  ${{/each}}
  </details>

  **Full Changelog**: ${{compareUrl}}
