name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  $COMMIT_MESSAGES

template-variables:
  COMMIT_MESSAGES: $COMMITS_TEMPLATE

replacers:
  - search: '\$COMMITS_TEMPLATE'
    replace: >-
      ${{
        const commitMessages = commits.map(commit => {
          return commit.message.trim();
        });
        commitMessages.join('\n\n')
      }}
