name-template: "v$RESOLVED_VERSION 🌟"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚨 Breaking Changes"
    labels: ["breaking"]
    commit-types: ["break", "breaking"]
  
  - title: "✨ New Features"
    labels: ["feature"]
    commit-types: ["feat", "feature"]
  
  - title: "🐛 Bug Fixes"
    labels: ["bug"]
    commit-types: ["fix", "bugfix"]
  
  - title: "📚 Documentation"
    labels: ["documentation"]
    commit-types: ["docs"]
  
  - title: "🎨 Code Style"
    labels: ["style"]
    commit-types: ["style"]
  
  - title: "♻️ Code Refactoring"
    labels: ["refactor"]
    commit-types: ["refactor"]
  
  - title: "⚡ Performance"
    labels: ["performance"]
    commit-types: ["perf"]
  
  - title: "✅ Tests"
    labels: ["test"]
    commit-types: ["test"]
  
  - title: "📦 Dependencies"
    labels: ["dependencies"]
    commit-types: ["deps"]
    collapse-after: 3
  
  - title: "🔧 Chores"
    labels: ["chore"]
    commit-types: ["chore"]
  
  - title: "🏗️ Build System"
    labels: ["build"]
    commit-types: ["build"]
  
  - title: "🌐 CI/CD"
    labels: ["ci"]
    commit-types: ["ci"]
  
  - title: "📋 Other Changes"
    labels: []
    commit-types: []

commit-parser:
  pattern: "^(\w+)(?:\(([\w\-\.]+)\))?(!)?:\s*(.+)$"
  map:
    break: "🚨 Breaking Changes"
    breaking: "🚨 Breaking Changes"
    feat: "✨ New Features"
    fix: "🐛 Bug Fixes"
    docs: "📚 Documentation"
    style: "🎨 Code Style"
    refactor: "♻️ Code Refactoring"
    perf: "⚡ Performance"
    test: "✅ Tests"
    deps: "📦 Dependencies"
    chore: "🔧 Chores"
    build: "🏗️ Build System"
    ci: "🌐 CI/CD"

change-template: |
  - $TITLE$SCOPE – by $AUTHOR in #$NUMBER

category-template: |
  ## $CATEGORY_TITLE
  $COMMITS

template-variables:
  CATEGORY_TITLE: $CATEGORY_TITLE_WITH_EMOJI
  SCOPE: $SCOPE_TEMPLATE
  AUTHOR: $COMMIT_AUTHOR

replacers:
  - search: '\$CATEGORY_TITLE_WITH_EMOJI'
    replace: >-
      ${{
        title === 'Breaking Changes' && '🚨 Breaking Changes' ||
        title === 'New Features' && '✨ New Features' ||
        title === 'Bug Fixes' && '🐛 Bug Fixes' ||
        title === 'Documentation' && '📚 Documentation' ||
        title === 'Code Style' && '🎨 Code Style' ||
        title === 'Code Refactoring' && '♻️ Code Refactoring' ||
        title === 'Performance' && '⚡ Performance' ||
        title === 'Tests' && '✅ Tests' ||
        title === 'Dependencies' && '📦 Dependencies' ||
        title === 'Chores' && '🔧 Chores' ||
        title === 'Build System' && '🏗️ Build System' ||
        title === 'CI/CD' && '🌐 CI/CD' ||
        title === 'Other Changes' && '📋 Other Changes' ||
        title
      }}

  - search: '\$SCOPE_TEMPLATE'
    replace: >-
      ${{
        scope ? ` **(${scope})**` : ''
      }}

  - search: '\$COMMIT_AUTHOR'
    replace: >-
      ${{
        author ? `@${author.split(' ')[0]}` : 'Unknown'
      }}

  - search: '^- '
    replace: >-
      ${{
        type === 'break' && '- 🚨 ' ||
        type === 'breaking' && '- 🚨 ' ||
        type === 'feat' && '- ✨ ' ||
        type === 'fix' && '- 🐛 ' ||
        type === 'docs' && '- 📚 ' ||
        type === 'style' && '- 🎨 ' ||
        type === 'refactor' && '- ♻️ ' ||
        type === 'perf' && '- ⚡ ' ||
        type === 'test' && '- ✅ ' ||
        type === 'deps' && '- 📦 ' ||
        type === 'chore' && '- 🔧 ' ||
        type === 'build' && '- 🏗️ ' ||
        type === 'ci' && '- 🌐 ' ||
        '- 📋 '
      }}

exclude:
  commits:
    - "^Merge"
    - "^Revert"
    - "^chore\(release\):"
    - "^docs\(changelog\):"

include:
  commit-hash: false
  commit-author: true
  commit-date: false

sort:
  by: "date"
  order: "desc"
