# .github/release.yaml (or .github/release-drafter.yml)
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'ci'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
  - title: '📖 Documentation'
    labels:
      - 'docs'
  - title: 'Other Changes'
    labels:
      - '*'
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: $PREVIOUS_TAG...$NEXT_TAG
