name-template: 'v$RESOLVED_VERSION 🌟'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    regex: 'feat'
  - title: '🐛 Bug Fixes'
    regex: 'fix'
  - title: '📚 Documentation'
    regex: 'doc'
  - title: '🔧 Other Changes'
    regex: '.*'

template: |
  ## What's Changed 🌟
  
  $CHANGES
  
  **Full Changelog**: $URL

change-template: |
  {% if commit.message %}${{addEmoji(commit.message)}}{% else %}${{addEmoji(pull_request.title)}}{% endif %} by @$AUTHOR (#$NUMBER)

addEmoji: |
  function(message) {
    const lowerMessage = message.toLowerCase();
    
    if (lowerMessage.includes('feat')) return '🚀 ' + message;
    if (lowerMessage.includes('fix')) return '🐛 ' + message;
    if (lowerMessage.includes('doc')) return '📚 ' + message;
    if (lowerMessage.includes('test')) return '✅ ' + message;
    if (lowerMessage.includes('spring') || lowerMessage.includes('boot')) return '🌐 ' + message;
    if (lowerMessage.includes('api')) return '📱 ' + message;
    if (lowerMessage.includes('config')) return '🔧 ' + message;
    
    return '🔧 ' + message;
  }
