changelog:
  categories:
    - title: "⚠️ BREAKING CHANGES"
      labels: ["breaking-change"]

    - title: "🐞 Defect Fixes"
      labels: ["bug", "hotfix"]
      body: |
        {{#each commits}}
        - {{this.subject}} {{#if (hasLabels this.labels "origination")}}(Origination){{/if}}{{#if (hasLabels this.labels "maintenance")}}(Maintenance){{/if}}{{#if (hasLabels this.labels "attestation")}}(Attestation){{/if}} ([#{{this.pr}}]({{this.pr_url}}))
        {{/each}}

    - title: "✨ New Features"
      labels: ["feature", "enhancement"]
      body: |
        {{#each commits}}
        - {{this.subject}} {{#if (hasLabels this.labels "origination")}}(Origination){{/if}}{{#if (hasLabels this.labels "maintenance")}}(Maintenance){{/if}}{{#if (hasLabels this.labels "attestation")}}(Attestation){{/if}} ([#{{this.pr}}]({{this.pr_url}}))
        {{/each}}

    - title: "🔄 API Updates"
      labels: ["api-update"]

    - title: "📦 Dependency Updates"
      labels: ["dependencies"]
      collapse: true

    - title: "📚 Documentation"
      labels: ["documentation"]
      collapse: true

    - title: "⚙️ Other Changes"
      labels: ["*"]
