name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels: ["feature"]
    # Also match commit messages starting with feat:/feature:
    collapse: false
  - title: "🐛 Bug Fixes"
    labels: ["bug"]
    # Also match commit messages starting with fix:/bug:
    collapse: false
  - title: "📚 Documentation"
    labels: ["documentation"]
    # Also match commit messages starting with docs:
    collapse: false
  - title: "⚡ Performance Improvements"
    labels: ["performance"]
    # Also match commit messages starting with perf:
    collapse: false
  - title: "🔧 Refactors"
    labels: ["refactor"]
    collapse: false
  - title: "✅ Tests"
    labels: ["test"]
    collapse: false
  - title: "📦 Chores"
    labels: ["chore"]
    collapse: false
  - title: "📋 Other Changes"
    labels: []
    collapse: false

# Simple template that uses the built-in categorization
template: |
  # v$RESOLVED_VERSION ($(date +'%Y-%m-%d'))
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

# Change template for individual items
change-template: |
  - $TITLE ([${commit.sha.substring(0, 7)}]${commit.author ? ' by @' + commit.author.login : ''})

# Template if there are no changes
no-changes-template: "No significant changes."

# Configuration
include-paths: []
exclude-labels: ["skip-changelog"]
sort-direction: ascending
sort-by: committed_date
