name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Categories based on conventional commit types
categories:
  - title: "🚨 Breaking Changes"
    labels: ["breaking-change"]
    commit-types: ["breaking", "break"]
  
  - title: "✨ Features"
    labels: ["feature"]
    commit-types: ["feat", "feature"]
  
  - title: "🐛 Bug Fixes"
    labels: ["bug"]
    commit-types: ["fix", "bug", "bugfix"]
  
  - title: "📚 Documentation"
    labels: ["documentation"]
    commit-types: ["docs"]
  
  - title: "🎨 Style Improvements"
    labels: ["style"]
    commit-types: ["style"]
  
  - title: "♻️ Refactoring"
    labels: ["refactor"]
    commit-types: ["refactor"]
  
  - title: "⚡ Performance"
    labels: ["performance"]
    commit-types: ["perf"]
  
  - title: "✅ Tests"
    labels: ["test"]
    commit-types: ["test"]
  
  - title: "🔧 Chores & Maintenance"
    labels: ["chore"]
    commit-types: ["chore"]
  
  - title: "📦 Dependencies"
    labels: ["dependencies"]
    commit-types: ["deps"]
    collapse-after: 2
  
  - title: "📋 Other Changes"
    labels: []
    commit-types: []

# Commit message parser configuration
commit-parser:
  pattern: "^(\w+)(?:\(([\w\-\.]+)\))?(!)?:\s*(.+)$"
  map:
    feat: "✨ Features"
    fix: "🐛 Bug Fixes" 
    docs: "📚 Documentation"
    style: "🎨 Style Improvements"
    refactor: "♻️ Refactoring"
    perf: "⚡ Performance"
    test: "✅ Tests"
    chore: "🔧 Chores & Maintenance"
    deps: "📦 Dependencies"
    breaking: "🚨 Breaking Changes"

# Template for changes
change-template: |
  - $TITLE$SCOPE – $AUTHOR (#$NUMBER)

# Category template to wrap each section
category-template: |
  ## $CATEGORY_TITLE
  $COMMITS

# Template variables
template-variables:
  CATEGORY_TITLE: $CATEGORY_TITLE_WITH_EMOJI
  SCOPE: $SCOPE_TEMPLATE
  AUTHOR: $COMMIT_AUTHOR

# Replacers for dynamic content
replacers:
  # Add emoji to category title
  - search: '\$CATEGORY_TITLE_WITH_EMOJI'
    replace: >-
      ${{
        title === 'Breaking Changes' && '🚨 Breaking Changes' ||
        title === 'Features' && '✨ Features' ||
        title === 'Bug Fixes' && '🐛 Bug Fixes' ||
        title === 'Documentation' && '📚 Documentation' ||
        title === 'Style Improvements' && '🎨 Style Improvements' ||
        title === 'Refactoring' && '♻️ Refactoring' ||
        title === 'Performance' && '⚡ Performance' ||
        title === 'Tests' && '✅ Tests' ||
        title === 'Chores & Maintenance' && '🔧 Chores & Maintenance' ||
        title === 'Dependencies' && '📦 Dependencies' ||
        title === 'Other Changes' && '📋 Other Changes' ||
        title
      }}
  
  # Add scope if present
  - search: '\$SCOPE_TEMPLATE'
    replace: >-
      ${{
        scope ? ` (${scope})` : ''
      }}
  
  # Format author name
  - search: '\$COMMIT_AUTHOR'
    replace: >-
      ${{
        author ? `@${author.split(' ')[0]}` : ''
      }}
  
  # Add emoji to individual commit based on type
  - search: '^- '
    replace: >-
      ${{
        type === 'feat' && '- ✨ ' ||
        type === 'fix' && '- 🐛 ' ||
        type === 'docs' && '- 📚 ' ||
        type === 'style' && '- 🎨 ' ||
        type === 'refactor' && '- ♻️ ' ||
        type === 'perf' && '- ⚡ ' ||
        type === 'test' && '- ✅ ' ||
        type === 'chore' && '- 🔧 ' ||
        type === 'deps' && '- 📦 ' ||
        type === 'breaking' && '- 🚨 ' ||
        '- 📋 '
      }}

# Exclude patterns
exclude:
  commits:
    - "^Merge"
    - "^Revert"
    - "^chore\(release\):"
    - "^docs\(changelog\):"

# Include options
include:
  commit-hash: false
  commit-author: true
  commit-date: false

# Sorting
sort:
  by: "date"
  order: "desc"
