name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  ## Changes
  $CHANGES
 
categories:
  - title: "🚨 Breaking Changes"
    labels: ["breaking-change"]
  - title: "✨ Features"
    labels: ["feature"]
  - title: "🐛 Bug Fixes"
    labels: ["bug"]
  - title: "🛠 Enhancements"
    labels: ["enhancement"]
  - title: "📦 Dependencies"
    labels: ["dependencies"]
    collapse-after: 2
  - title: "📋 Other Changes"
    labels: []
    # fallback bucket when PRs don't match above categories
 
label-extractors:
  module:
    labels:
      - origination
      - maintenance
      - testation

change-template: |
  - $TITLE$IS_MODULE – #$NUMBER

template-variables:
  IS_MODULE: $IS_MODULE_TEMPLATE

replacers:
  - search: '\$IS_MODULE_TEMPLATE'
    replace: >-
      ${{
        contains(labels, 'origination') && ' (`origination`)' ||
        contains(labels, 'maintenance') && ' (`maintenance`)' ||
        contains(labels, 'testation') && ' (`testation`)' ||
        ''
      }}
