name-template: "v$RESOLVED_VERSION 🚀"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚨 Breaking Changes"
    labels: ["breaking-change"]
    
  - title: "✨ New Features"
    labels: ["feature"]
    
  - title: "🐛 Bug Fixes" 
    labels: ["bug"]
    
  - title: "📚 Documentation"
    labels: ["documentation"]
    
  - title: "🔧 Chores & Maintenance"
    labels: ["chore"]
    
  - title: "📦 Dependencies"
    labels: ["dependencies"]
    
  - title: "📋 Other Changes"
    labels: []

# CRITICAL: This forces commit parsing instead of PR parsing
template: |
  ## What's Changed
  $CHANGES

# Use this simple template for each change
change-template: |
  - $TITLE by @$AUTHOR

# This groups commits by category with emoji headers
category-template: |
  ### $TITLE
  $COMMITS

# Proper commit parsing configuration
commit-parser:
  pattern: "^(\w+)(?:\(([\w\-\.]+)\))?!?:\s*(.+)$"
  map:
    feat: "✨ New Features"
    fix: "🐛 Bug Fixes" 
    docs: "📚 Documentation"
    chore: "🔧 Chores & Maintenance"
    deps: "📦 Dependencies"

# Add emojis based on commit type
replacers:
  - search: '^- '
    replace: |-
      ${{
        (commit.match(/^feat:/) || commit.match(/^feature:/)) && '- ✨ ' ||
        (commit.match(/^fix:/) || commit.match(/^bug:/)) && '- 🐛 ' ||
        (commit.match(/^docs:/) || commit.match(/^documentation:/)) && '- 📚 ' ||
        (commit.match(/^chore:/) || commit.match(/^maintenance:/)) && '- 🔧 ' ||
        (commit.match(/^deps:/) || commit.match(/^dependencies:/)) && '- 📦 ' ||
        '- 📋 '
      }}

exclude:
  commits:
    - "^Merge"
    - "^Revert"
    - "^chore\(release\):"
    - "^docs\(changelog\):"

include:
  commit-hash: false
  commit-author: true
  commit-date: false

sort:
  by: "date"
  order: "desc"
