# .github/workflows/generate-changelog.yml
name: Generate Changelog

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      tag_name:
        description: 'Release tag (e.g., v1.0.0)'
        required: true

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          tag: ${{ github.event.inputs.tag_name }}  # Use manually provided tag
          disable-autolabeler: true  # Skip auto-labeling
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
