name: 📦 Create Draft Release (Manual)
 
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.2.3)'
        required: true
        type: string
 
jobs:
  update_release_draft:
    name: 🛠 Run Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: 🧰 Run release-drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
